/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Audio: typeof import('./src/steps/audio.vue')['default']
    Btn: typeof import('./src/components/btn.vue')['default']
    Clip: typeof import('./src/steps/clip.vue')['default']
    Cover: typeof import('./src/steps/cover.vue')['default']
    FloatingEntry: typeof import('./src/components/FloatingEntry.vue')['default']
    Info: typeof import('./src/steps/info.vue')['default']
    Lyrics: typeof import('./src/steps/lyrics.vue')['default']
    LyricsTimeline: typeof import('./src/components/LyricsTimeline.vue')['default']
    Picker: typeof import('./src/steps/picker.vue')['default']
    TaskCenter: typeof import('./src/components/TaskCenter.vue')['default']
    UiAlert: typeof import('./src/components/UiAlert.vue')['default']
    UiButton: typeof import('./src/components/UiButton.vue')['default']
    UiButtonGroup: typeof import('./src/components/UiButtonGroup.vue')['default']
    UiCheckbox: typeof import('./src/components/UiCheckbox.vue')['default']
    UiDropdown: typeof import('./src/components/UiDropdown.vue')['default']
    UiFormItem: typeof import('./src/components/UiFormItem.vue')['default']
    UiInput: typeof import('./src/components/UiInput.vue')['default']
    UiInputGroup: typeof import('./src/components/UiInputGroup.vue')['default']
    UiMessage: typeof import('./src/components/UiMessage.vue')['default']
    UiModal: typeof import('./src/components/UiModal.vue')['default']
    UiResult: typeof import('./src/components/UiResult.vue')['default']
    UiSelect: typeof import('./src/components/UiSelect.vue')['default']
    UiSpace: typeof import('./src/components/UiSpace.vue')['default']
    UiSpin: typeof import('./src/components/UiSpin.vue')['default']
    UiSteps: typeof import('./src/components/UiSteps.vue')['default']
    UiTabs: typeof import('./src/components/UiTabs.vue')['default']
    UiTextarea: typeof import('./src/components/UiTextarea.vue')['default']
  }
}
